upstream backend_cluster {
    server 192.168.1.50:443;
}

# 1. HTTP so'rovlarni HTTPS ga yo'naltirish
server {
    listen 80;
    server_name vault-srv.trustbank.uz;
    return 301 https://$host$request_uri;
}

# 2. Asosiy HTTPS Reverse Proxy
server {
    listen 443 ssl;
    server_name vault-srv.trustbank.uz;

    ssl_certificate     /etc/ssl/certs/vault.crt;
    ssl_certificate_key /etc/ssl/private/vault.key;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    location / {
        proxy_pass https://backend_cluster;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_ssl_verify off;

        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
    }
}
