server {
    listen 80;
    server_name _;

    # HAProxy Health-Check so'rovi uchun (200 OK qaytaradi)
    location /health {
        access_log off;
        return 200 "healthy\n";
        add_header Content-Type text/plain;
    }

    location / {
        root /var/www/html;
        index index.html;
    }
}
