global_defs {
    router_id nginx_backup
    script_user root
    enable_script_security
}

vrrp_script chk_nginx {
    script "/usr/local/bin/check_nginx.sh"
    interval 2
    weight 2
}

vrrp_instance VI_NGINX {
    state BACKUP
    interface ens33
    virtual_router_id 51
    priority 100
    advert_int 1

    authentication {
        auth_type PASS
        auth_pass NginxSecretPass123
    }

    virtual_ipaddress {
        192.168.1.100/24 dev ens33
    }

    track_script {
        chk_nginx
    }
}
